const ExercisePlan = {
    "days": {
        "monday": [
            "squat",
            "calfRaise",
            "overheadPress",
            "skullCrusher",
            "crunch",
            "powerClean"
        ],
        "wednesday": [
            "deadlifts",
            "lunges",
            "benchPress",
            "pushup",
            "ankleTouch",
            "squatJump"
        ],
        "friday": [
            "squat",
            "goodMorning",
            "pendlay",
            "curling",
            "sidePlank",
            "burpees"
        ]
    },
    "exercises": {
       "squat":{
          "warmups":[
             45,
             45,
             95
          ],
          "sets":[
             140,
             140,
             140
          ]
       },
       "calfRaise":{
          "sets":[
             65,
             65,
             65
          ]
       },
       "overheadPress":{
          "warmups":[
             45,
             55,
             60
          ],
          "sets":[
             65,
             65,
             65
          ]
       },
       "skullCrusher":{
          "sets":[
             135,
             135,
             135
          ]
       },
       "crunch":{
          "sets":[
             0,
             0,
             0
          ]
       },
       "powerClean":{
          "warmups":[
             55,
             55,
             95
          ],
          "sets":[
             95,
             95,
             95
          ]
       },
       "deadlifts":{
          "warmups":[
             135
          ],
          "sets":[
             135,
             155,
             185
          ]
       },
       "lunges":{
          "sets":[
             0,
             0,
             0
          ]
       },
       "benchPress":{
          "warmups":[
             45,
             65,
             85
          ],
          "sets":[
             85,
             85,
             85
          ]
       },
       "pushup":{
          "sets":[
             0,
             0,
             0
          ]
       },
       "ankleTouch":{
          "sets":[
             0,
             0,
             0
          ]
       },
       "squatJump":{
          "sets":[
             0,
             0,
             0
          ]
       },
       "goodMorning":{
          "sets":[
             65,
             65,
             65
          ]
       },
       "pendlay":{
          "warmups":[
             45,
             45,
             65
          ],
          "sets":[
             75,
             75,
             75
          ]
       },
       "curling":{
          "sets":[
             55,
             55,
             55
          ]
       },
       "sidePlank":{
          "sets":[
             0,
             0,
             0
          ]
       },
       "burpees":{
          "sets":[
             0,
             0,
             0
          ]
       }
    }
};

export default ExercisePlan;